### ISSUE TITLE
missing argument to charm_tracing breaks the charm when integrated to Tempo

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/self-signed-certificates-operator#208]
### Bug Description

the trace_charm decorator will raise an exception if you pass to it an https `endpoint` but no `server_cert`.

### To Reproduce

juju deploy self-signed-certificates ssc
juju deploy traefik-k8s traefik  # might not be necessary
juju deploy tempo-k8s tempo

jhack imatrix fill

### Environment

juju 3.5

### Relevant log output

```shell
unit-ssc-0: 11:55:39 ERROR unit.ssc/0.juju-log certificates:39: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-ssc-0/charm/./src/charm.py", line 341, in <module>
    main(SelfSignedCertificatesCharm)
  File "/var/lib/juju/agents/unit-ssc-0/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-ssc-0/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-ssc-0/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-ssc-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 450, in wrap_init
    raise TLSError(
charms.tempo_k8s.v1.charm_tracing.TLSError: Tracing endpoint is https, but no server_cert has been passed.Please point @trace_charm to a `s
rver_cert` attr.
unit-ssc-0: 11:55:39 ERROR juju.worker.uniter.operation hook "certificates-relation-changed" (via hook dispatching script: dispatch) failed
 exit status 1
unit-ssc-0: 11:55:39 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
```

**Comment by PietroPasotti** [comment]
added a partial solution to https://github.com/canonical/self-signed-certificates-operator/pull/209

some help is needed to figure out how to solve it exactly
