### ISSUE TITLE
Short-lived error on charm upgrade

### ISSUE THREAD

**Issue by sed-i** [canonical/self-signed-certificates-operator#33]
On charm upgrade I noticed the following error:

```
unit-external-ca-0: 16:18:20.238 ERROR unit.external-ca/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-external-ca-0/charm/venv/ops/model.py", line 2792, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-external-ca-0/secret-get', '--label', 'ca-certificates', '--format=json')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-external-ca-0/charm/./src/charm.py", line 267, in <module>
    main(SelfSignedCertificatesCharm)
  File "/var/lib/juju/agents/unit-external-ca-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-external-ca-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-external-ca-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-external-ca-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-external-ca-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-external-ca-0/charm/./src/charm.py", line 163, in _configure_ca
    self._generate_root_certificate()
  File "/var/lib/juju/agents/unit-external-ca-0/charm/./src/charm.py", line 138, in _generate_root_certificate
    secret = self.model.get_secret(label=CA_CERTIFICATES_SECRET_LABEL)
  File "/var/lib/juju/agents/unit-external-ca-0/charm/venv/ops/model.py", line 272, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-external-ca-0/charm/venv/ops/model.py", line 3148, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-external-ca-0/charm/venv/ops/model.py", line 2794, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: ERROR getting cluster client: unable to determine legacy status for namespace "trfk": namespaces "trfk" is forbidden: User "system:serviceaccount:trfk:unit-external-ca-0" cannot get resource "namespaces" in API group "" in the namespace "trfk"
```

This quickly resolves itself and the upgrade sequence results in active/idle.
I haven't worked with secrets yet but I wonder if some sort of readiness guard is missing.

**Comment by gruyaume** [comment]
This seems to be related to a bug in Juju:

https://bugs.launchpad.net/juju/+bug/2032686

We have seen similar issues in other charms (ex. Vault-k8s)

**Comment by gruyaume** [comment]
Closing as this affects any charm using get_secret and is not specific to this one
