### ISSUE TITLE
Extension already set when using with postgresql

### ISSUE THREAD

**Issue by Martwall** [canonical/self-signed-certificates-operator#38]
I'm testing the postgresql charm locally on lxd with self-signed-certificates charm and getting the following error:

```shell
unit-self-signed-certificates-0: 14:20:26 ERROR unit.self-signed-certificates/0.juju-log certificates:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/./src/charm.py", line 267, in <module>
    main(SelfSignedCertificatesCharm)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 342, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 839, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 928, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 1180, in _on_relation_changed
    self.on.certificate_creation_request.emit(
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 342, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 839, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 928, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/./src/charm.py", line 204, in _on_certificate_creation_request
    certificate = generate_certificate(
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 756, in generate_certificate
    certificate_builder = certificate_builder.add_extension(
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/cryptography/x509/base.py", line 910, in add_extension
    _reject_duplicate_extension(extension, self._extensions)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/cryptography/x509/base.py", line 68, in _reject_duplicate_extension
    raise ValueError("This extension has already been set.")
ValueError: This extension has already been set.
unit-self-signed-certificates-0: 14:20:26 ERROR juju.worker.uniter.operation hook "certificates-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

replicate:
```shell
juju deploy postgresql
juju deploy self-signed-certificates --channel edge
juju integrate self-signed-certificates postgresql
```

**Comment by gruyaume** [comment]
Thanks for reporting this, I've added this to our next pulse.

**Comment by gruyaume** [comment]
I noticed the postgresql charm uses TLS lib v1.12 while the self-signed certificates operator is already at v2.16. I'd suggest to bump the lib in the postgresql charm. Please report back if the issue persists.

**Comment by Martwall** [comment]
Thank you! I'll report it over at the postgresql-operator repo.

**Comment by gruyaume** [comment]
I'll close the issue here then, as mentioned above please re-open it if it persists after using the latest version of the lib.
