### ISSUE TITLE
Error After Relation with 'postgresql_client' Interface

### ISSUE THREAD

**Issue by mertalpt** [canonical/self-signed-certificates-operator#52]
After the initial report on the Matrix channel, I was requested to report this as a bug.

### Reproduction
Run the following commands in a Juju 3.1.6 VM model.
```sh
juju deploy postgresql --channel 14/stable
juju deploy self-signed-certificates --channel edge
juju relate postgresql self-signed-certificates
```
### Expected Behavior
After the relation is formed, charms settle on `active + idle` and we have TLS on `postgresql`.

### Actual Behavior
```
ubuntu@main:~$ juju status --relations
Model        Controller  Cloud/Region         Version  SLA          Timestamp
welcome-lxd  lxd         localhost/localhost  3.1.6    unsupported  16:17:50+03:00

App                       Version  Status  Scale  Charm                     Channel    Rev  Exposed  Message
postgresql                14.9     active      1  postgresql                14/stable  351  no
self-signed-certificates           error       1  self-signed-certificates  edge        56  no       hook failed: "certificates-relation-changed"

Unit                         Workload  Agent  Machine  Public address  Ports     Message
postgresql/1*                active    idle   1        10.117.236.247  5432/tcp
self-signed-certificates/0*  error     idle   2        10.117.236.207            hook failed: "certificates-relation-changed" for postgresql:certificates

Machine  State    Address         Inst id        Base          AZ  Message
1        started  10.117.236.247  juju-b98bfe-1  ubuntu@22.04      Running
2        started  10.117.236.207  juju-b98bfe-2  ubuntu@22.04      Running

Integration provider                   Requirer                   Interface         Type     Message
postgresql:database-peers              postgresql:database-peers  postgresql_peers  peer
postgresql:restart                     postgresql:restart         rolling_op        peer
postgresql:upgrade                     postgresql:upgrade         upgrade           peer
self-signed-certificates:certificates  postgresql:certificates    tls-certificates  regular
```

, and output excerpt from `juju debug-log --include self-signed-certificates`

```
unit-self-signed-certificates-0: 16:17:00 DEBUG unit.self-signed-certificates/0.juju-log certificates:8: ops 2.9.0 up and running.
unit-self-signed-certificates-0: 16:17:00 DEBUG unit.self-signed-certificates/0.juju-log certificates:8: Emitting Juju event certificates_relation_changed.
unit-self-signed-certificates-0: 16:17:00 DEBUG unit.self-signed-certificates/0.juju-log certificates:8: Emitting custom event <CertificateCreationRequestEvent via SelfSignedCertificatesCharm/TLSCertificatesProvidesV2[certificates]/on/certificate_creation_request[37]>.
unit-self-signed-certificates-0: 16:17:00 ERROR unit.self-signed-certificates/0.juju-log certificates:8: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/./src/charm.py", line 313, in <module>
    main(SelfSignedCertificatesCharm)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 1222, in _on_relation_changed
    self.on.certificate_creation_request.emit(
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/./src/charm.py", line 233, in _on_certificate_creation_request
    self._generate_self_signed_certificate(
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/./src/charm.py", line 249, in _generate_self_signed_certificate
    certificate = generate_certificate(
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 796, in generate_certificate
    certificate_builder = certificate_builder.add_extension(
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/cryptography/x509/base.py", line 910, in add_extension
    _reject_duplicate_extension(extension, self._extensions)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/cryptography/x509/base.py", line 68, in _reject_duplicate_extension
    raise ValueError("This extension has already been set.")
ValueError: This extension has already been set.
unit-self-signed-certificates-0: 16:17:00 ERROR juju.worker.uniter.operation hook "certificates-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by gruyaume** [comment]
Thank you for reaching out @mertalpt , I will look into this issue

**Comment by gruyaume** [comment]
Hello @mertalpt 

In summary, this issue occured because the TLS requirer, in this case postgresql manually adds a x.509 extension that should only be set by the TLS provider. 

Here is what needs to happen:

1. Update the TLS Certificates Interface to ignore extensions coming from the CSR that should be set by the TLS provider and log those to inform the user. Here's the PR for this: https://github.com/canonical/tls-certificates-interface/pull/96
2. Update the self-signed certificates to use this new version of the lib.
3. Update the `postgresql` charm to use the `is_ca` parameter when generating certs instead of manually adding the x.509 extension.

**Comment by gruyaume** [comment]
@marceloneppel , I recommend that you bump the TLS lib version to 2.21 in the postgresl charms. Also make sure to use the `is_ca` parameter instead of manually specifying the x.509 Basic constraints extension.

Reference:
- https://github.com/canonical/tls-certificates-interface/blob/main/lib/charms/tls_certificates_interface/v2/tls_certificates.py#L1533C12-L1533C12

**Comment by marceloneppel** [comment]
Thanks @gruyaume. I'll update both charms with your recommendations.

**Comment by marceloneppel** [comment]
Hi @mertalpt! The issue was fixed in the PostgreSQL charm by revision 363 (from the 14/stable channel).

**Comment by mertalpt** [comment]
Thanks for the heads up @marceloneppel !
