### ISSUE TITLE
Charm goes into error state with KeyError: 'is_ca' 

### ISSUE THREAD

**Issue by markbeierl** [canonical/self-signed-certificates-operator#56]
When deploying Charmed 5g SD-Core bundle, the ssc charm goes into error state with the following being observed in the juju debug-log:

```
unit-self-signed-certificates-0: 12:53:21 ERROR unit.self-signed-certificates/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/./src/charm.py", line 313, in <module>
    main(SelfSignedCertificatesCharm)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/./src/charm.py", line 180, in _configure
    self._process_outstanding_certificate_requests()
  File "/var/lib/juju/agents/unit-self-signed-certificates-0/charm/./src/charm.py", line 198, in _process_outstanding_certificate_requests
    is_ca=request["is_ca"],
KeyError: 'is_ca'
```

**Comment by gruyaume** [comment]
Taken from the matrix convo with Mark:

```
self-signed-certificates           waiting      1  self-signed-certificates  beta            57  10.152.183.150  no       installing agent
```

So this is affecting revison 56 (beta)
